use_frameworks!

platform :ios, '8.0'

target 'WPMarkDownParse_Example' do
  pod 'WPMarkDownParse', :path => '../'
  pod 'WPBaseTableView'
  target 'WPMarkDownParse_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
